"""
Django settings for blog_dj project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import  os
from  decouple import config
from dj_database_url import parse as dburl
import django_heroku


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG',default=False,cast=bool)

# para adicionar endereço dns
# ... exemplo.com.br
ALLOWED_HOSTS = ['*','https://blog-djangopy.herokuapp.com']
#blog-djangopy
# https://git.heroku.com/blog-djangopy.git
# https://blog-django-py.herokuapp.com/ "

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrapform',
    'ckeditor',
    #'app_blog'
    'app_blog.apps.AppBlogConfig',
    'accounts',
    'social',
    'contact'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        #'DIRS': [],
        #'DIRS': [BASE_DIR / 'templates']
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.processors.ctk_Social',
            ],
        },
    },
]


WSGI_APPLICATION = 'blog_dj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

default_dburl = 'sqlite:////' + os.path.join(BASE_DIR,'db.sqlite3')
DATABASES = {'default':config('DATABASES_URL',default=default_dburl,cast=dburl)}
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'pt-br'

#TIME_ZONE = 'UTC'

#FUSO HORARIO DO BRAZIL
TIME_ZONE = 'America/Fortaleza'


USE_I18N = True

USE_L10N = True

USE_TZ = True

#LOGIN

LOGIN_REDIRECT_URL = 'home'

#LOGIN
LOGOUT_REDIRECT_URL = 'home'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/



MEDIA_URL = '/media/'

MEDIA_ROOT = 'media'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    'statics'
]

STATIC_URL = '/static/'

EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = '02e8c5f14cc078'
EMAIL_HOST_PASSWORD = '03de180b45957c'
EMAIL_PORT = '2525'

#debug
'''com a inclusão do EMAIL_BACKEND  o email não é envdado para o servidor smtp 
e sim para o terminal para verificação de erros. isso é para testes '''
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

django_heroku.settings(locals())