# Generated by Django 3.1.4 on 2021-01-05 18:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20210102_1603'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('publishedManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
