# Generated by Django 3.1.4 on 2021-01-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20210105_1546'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
